### ISSUE TITLE
Repeated warning on critical level

### ISSUE THREAD

**Issue by DianaProbst** [JarekSed/batterymon-clone#1]
I find that I use the critical warning to perform an action that warns me there is a problem, and I need to plug in my charger.  When the charger has been plugged in, I want the warning to stop.  If the --on-critical action is something like shut down, it doesn't matter if it's not repeated, but if the charger's in, I think the warning should stop.

Can I suggest that line 605, the first line of def battery_property_modified(self, battery), should read 

if int(battery.charge_level) <= int(self.power_level) and self.command and not battery.is_charging:

**Comment by JarekSed** [comment]
Fixed in commit 92726b20704381e551dce918410ca3d6b9972ccb
